project:
  type: book
  output-dir: docs

toc: true
number-sections: false
book:
  title: "HOLPA Key Performance and Agroecological Indicator Protocols"
  author: "Sarah K. Jones,a,* Andrea Cecilia Sánchez,a,b,c, Chris Dickensd, Matthias S. Gecke, Chaturangi Wickramaratned, Veronique Alaryf,g, Peter Boloh, Dennis Junior Chorumai, Somphasith Douangsavanhj, Modou Gueye Fallk, Gatien Falconnierl,m,n,o, Shweta Guptap,q, Chris Kettler, Smitha Krishnans, Sylvia Nyawirah, Guillermo Orjuela-Ramirezt, Boko Michel Orounladjiu, Piedad Parejav, Telma Sibandal, Christine Lamannae,1 "
  date: "12/5/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "1. Environmental KPIs"
      chapters:
        - kpis/environmental/crop_livestock_fish_diversity.qmd
        - kpis/environmental/insect_mammal_tree_diversity.qmd
        - kpis/environmental/landscape_complexity.qmd
        - kpis/environmental/water_stress.qmd
        - kpis/environmental/energy_use.qmd
        - kpis/environmental/climate_mitigation.qmd
    - part: "2. Agricultural KPIs"
      chapters:
        - kpis/agricultural/crop_health.qmd
        - kpis/agricultural/animal_health.qmd
        - kpis/agricultural/soil_health.qmd
        - kpis/agricultural/nutrient_use.qmd
    - part: "3. Social KPIs"
      chapters:
        - kpis/social/diet_quality.qmd
        - kpis/social/land_tenure_security.qmd
        - kpis/social/farmer_agency.qmd
        - kpis/social/human_well_being.qmd
    - part: "4. Economic KPIs"
      chapters:
        - kpis/economic/agricultural_productivity.qmd
        - kpis/economic/labour_productivity.qmd
        - kpis/economic/total_income_and_income_stability.qmd
        - kpis/economic/climate_resilience.qmd
    - part: "5. Complementary Indicators"
      chapters:
        - kpis/complementary/bat_bird_insect_diversity.qmd
        - kpis/complementary/pollinator_divertisy.qmd
        - kpis/complementary/soil_health_socla.qmd
        - kpis/complementary/nutrient_use_efficiency.qmd
        - kpis/complementary/nutrient_balance.qmd
        - kpis/complementary/greenhouse_gas_emissions.qmd
        - kpis/complementary/enteric_methane_emission_intensity.qmd


    - ae_indicators.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - flatly



